
// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Tue Oct  8 22:20:26 2019

`timescale 1ns/1ps

module test;

reg [2:0] opcode;
reg [4:0] sa;
reg [31:0] dat;
wire [31:0] res;
integer i = 0;


lab3_barrel_shifter bs
(
	.bs_opsel(opcode) ,	// input [2:0] opcode
	.shift_amount(sa) ,	// input [4:0] sa
	.in_data(dat) ,	// input [31:0] dat
	.o_result(res) 	// output [31:0] res
);


initial begin
	dat = 32'hbadbadba;
	sa = 0 ;
	#5 sa = 5'b1000;
	opcode = 0;
	for(i=0;i<=6;i=i+1)begin
		#5 opcode = i;
 	end
end

initial begin
	#40 $stop();
end

endmodule


